# Generated by Django 4.1.2 on 2023-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='app/src/images/defaultimage.jpg', upload_to='app/src/images/'),
        ),
    ]
